title: Nangtural02's Blog
description: Nangtural02's Tech Blog
theme: just-the-docs

url: https://nangtural02.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"